.186
EXTRN NUM: WORD
PUBLIC PRINT_BINARY_SIGNED

DATA_SEG SEGMENT PARA PUBLIC 'DATA'
    B_OUT DB 13, 10, 'Signed bin number: $'
    BIN_SYMB DB '01'
DATA_SEG ENDS

CODE_SEG SEGMENT PARA PUBLIC 'CODE'
    ASSUME CS:CODE_SEG, DS:DATA_SEG
    
SIGN_PROC PROC NEAR
    MOV AX, BX
    AND AX, 1000000000000000b
    SHR AX, 15

    CMP AX, 0
    JE PLUS

    CMP AX, 1
    JE MINUS

    MINUS:
    MOV AH, 02H
    MOV DL, '-'
    INT 21H
    NEG BX
    JMP FUNC_END

    PLUS:
    MOV AH, 02H
    MOV DL, '+'
    INT 21H
    JMP FUNC_END

    FUNC_END:
    SHL BX, 1
    RET
SIGN_PROC ENDP

PRINT_BINARY_SIGNED PROC NEAR
    MOV AH, 9H
    MOV DX, OFFSET B_OUT
    INT 21H
    MOV BX, NUM
    MOV CX, 15

    CALL SIGN_PROC
    PRINT:
        MOV AX, BX
        AND AX, 1000000000000000b
        SHR AX, 15

        MOV SI, AX
        MOV DL, BIN_SYMB[SI]
        MOV AH, 02H
        INT 21H

        SHL BX, 1

        loop PRINT
    RET        
PRINT_BINARY_SIGNED ENDP

CODE_SEG ENDS
END