.186
EXTRN NUM: WORD
PUBLIC PRINT_HEX_UNSIGNED

DATA_SEG SEGMENT PARA PUBLIC 'DATA'
    H_OUT DB 13, 10, 'Unsigned hex number: $'
    HEX_SYMB DB '0123456789ABCDEF'
DATA_SEG ENDS

CODE_SEG SEGMENT PARA PUBLIC 'CODE'
    ASSUME CS:CODE_SEG, DS:DATA_SEG
    

PRINT_HEX_UNSIGNED PROC NEAR
    MOV AH, 9H
    MOV DX, OFFSET H_OUT
    INT 21H
    MOV BX, NUM
    MOV CX, 4
    PRINT:
        MOV AX, BX
        AND AX, 1111000000000000b
        SHR AX, 12

        MOV SI, AX
        MOV DL, HEX_SYMB[SI]
        MOV AH, 02H
        INT 21H

        SHL BX, 4

        loop PRINT
    RET        
PRINT_HEX_UNSIGNED ENDP

CODE_SEG ENDS
END